version: "3.3"
services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.api.address=:5000"
    ports:
      - "80:80"
      - "8080:8080"
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  api:
    image: "yiyu0x/ptt-beauty-api:2.1"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`127.0.0.1`)"
      - "traefik.http.routers.api.entrypoints=api"
