version: '3.7'
services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    image: yiyu0x/ptt-beauty-api:2.1
    restart: "always"
    labels:
      - "traefik.http.routers.api.rule=Host(`*`)"
