name: CI/CD

on:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_REPO}}
        run: |
          docker build -t $DOCKER_IMAGE .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:latest
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: SSH into VPS
  #       uses: appleboy/ssh-action@v0.4.0
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USERNAME }}
  #         key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

  #     - name: Deploy on server
  #       run: |
  #         docker stop $DOCKER_IMAGE
  #         docker rm $DOCKER_IMAGE
  #         docker rmi $DOCKER_USERNAME/$DOCKER_IMAGE
  #         docker pull $DOCKER_USERNAME/$DOCKER_IMAGE:latest
  #         docker container run -d --name $DOCKER_IMAGE -p 5001:5487 $DOCKER_USERNAME/$DOCKER_IMAGE:latest
